version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - ./db:/app/db
  nginx:
    image: nginx
    ports:
      - 3080:3080
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
